# Generated by Django 4.2.7 on 2025-12-22 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
