# Generated by Django 4.2.7 on 2025-12-22 12:41

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_portfolioitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='photo',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_archive',
            field=models.FileField(blank=True, null=True, upload_to=cards.models.upload_to_portfolio, verbose_name='Архив проекта (zip)'),
        ),
    ]
