# Generated by Django 4.2.7 on 2025-12-22 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_portfolioitem_link_remove_testimonial_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="author",
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_testimonials",
                verbose_name="Автор отзыва",
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=150, verbose_name="Заголовок/роль"),
        ),
        migrations.RemoveField(
            model_name="user",
            name="theme_accent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="theme_mode",
        ),
    ]
