# Generated by Django 4.2.27 on 2025-12-23 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_add_author_to_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_testimonials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отзыва",
            ),
        ),
    ]
