# Generated by Django 4.2.27 on 2025-12-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_alter_testimonial_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Username аккаунта в MAX"
            ),
        ),
    ]
